### ISSUE TITLE
Klein @function with($namespace, $routes).

### ISSUE THREAD

**Issue by phpblocks** [klein/klein.php#122]
I don't know if this is an issue. But when you use $klein->with($namespace, $routes) it is always called even when the request url does not have the $namespace. I thought when you for instance called admin/users (admin/_) that the function with() is called and not when you call blog/article-slug (blog/_)?

Thanks in advance!

**Comment by silentFred** [comment]
@phpblocks i know this is a bit late but did you manage to implement something like laravel's filters for auth etc using klein? I'm in need of the same
