### ISSUE TITLE
Using Flash messages with OnError

### ISSUE THREAD

**Issue by Jrizzi1** [klein/klein.php#159]
I am a newb as far as php routing goes , so pls be gentle

I have some parameters I am validating , and am unsure how to tie it together with the onError and displaying it on the view

for instance , say this

```
$klein->respond('POST', '/new-data-request', function ($request, $response, $service, $app) {
       $service->validateParam('title', 'Title is a required field')->notNull();
        $service->render('myview.phtml');
});
```

myview.phtml never shows as i assume an error has triggered in the initial respond()

```
$klein->respond(function ($request, $response, $service, $app) use ($klein) {

$app->db = $db;

    $klein->onError(function ($klein, $err_msg) {
        $klein->service()->flash($err_msg);
        $klein->service()->back();
    });

    $service->layout('layout.phtml');
});
```

but i have no idea how to display the flash in the view, or how to tie this all together

**Comment by MauricioKruijer** [comment]
@Rican7 What doesn't make sense? The code provided looks almost identical to the code in the example ("Example 5 - All together" in README.md file) I'm a bit confused..

**Comment by doctorallen** [comment]
That is true, the README does show the onError in the response callback, but I do not believe this is desired behavior. If the onError is in a response callback (i'm not sure it would even work) but it would only catch errors generated before or inside that response, which would lead to you duplicating this same exact code in every response callback, when you can just add it once, at the bottom of your routes. Try this instead:
```php
$klein->respond('POST', '/new-data-request', function ($request, $response, $service, $app) {
       $service->validateParam('title', 'Title is a required field')->notNull();
       $service->render('myview.phtml');
});

$klein->onError(function ($klein, $err_msg) {
    $klein->service()->flash($err_msg);
    $klein->service()->back();
});
```
This will then respond to any errors, set a flash message, and then return the user back to the route they were viewing. You can then display the error message in that template with
```php
foreach ($service->flashes as $flash) {
    echo $flash;
}
```
There may be a better way of doing this, but looking at the ServiceProvider class, it looks like this is how it is used.
