### ISSUE TITLE
parmsJson feature 

### ISSUE THREAD

**Issue by ada** [klein/klein.php#165]
I would like to fetch parameters from a raw json source. 

I.e. I send ["username":"foo", "password":"bar"] to the route /user/login
and then I fetch the params like $request->paramsJson('username'); 

Any thoughts about implementing this feature? 

Great job, everybody.

**Comment by Djuka** [comment]
This is actually really easy to implement and it's is really handy to have this feature. But it's always easy to do:

    $json = file_get_contents('php://input');
    $json = json_decode($json);
