### ISSUE TITLE
Implementing a catch all route

### ISSUE THREAD

**Issue by CMCDragonkai** [klein/klein.php#166]
How would Klein be able to setup a catch all route? So I can go through a list of rules and if none of them matched, use this last one?

**Comment by teliov** [comment]
Just an adjustment to @Rican7 's answer for Klein 2.1 dev
// Klein current master (2.1 dev) style:
$klein->respond(function($request, $response, $service, $app, $klein, $matched) {
    if (count($matched->all()) > 0) {
        // We must have matched a route earlier so do nothing
    } else {
        // I guess we didn't match anything earlier, let's go home..., do what you like
    }
});

$matched > 0 alone did not work for me.
