### ISSUE TITLE
Best practice for login redirect?

### ISSUE THREAD

**Issue by eimajenthat** [klein/klein.php#174]
What's the best way to catch unauthenticated users and redirect them to a login page with Klein?  I can see a couple ways that seem like they might work, but I'm looking for a best practice that can be agreed upon by smarter folks than me.

All of my routes actually get pointed to an assortment of Controller classes, which have a common parent.  So potentially, I could do the login check in the constructor for the super class.

Or I could put a catch all route that does a login check.

Either solution seems workable, although in both cases, I need a way to exempt certain public routes (most notably the login page itself).  I can just make my own validation here, like create an array of routes, and if it's in that array, we skip the login check.  Or perhaps always run the login check, but have the login check function own the logic for allowing certain routes to pass without auth.

But I would be very interested in hearing how others are doing this.

On a similar note, Symfony2 has a clever firewall feature.  In one of the countless Yaml files Sf2 projects seem to generate, you can specify privileges required to access certain routes.  I was thinking about setting up something similar with Klein.  Again, I was thinking a catch all route which validated the user's permissions against the permissions required for the current route path, and threw a 403 error if they didn't validate, but I would be curious if anyone has built something like this with Klein, and if they had any wisdom to share.

If someone wanted to jot some notes on their experiences, I'd be happy to polish it into a Wiki page.

**Comment by funkytaco** [comment]
>if you're using the newest Klein master (not yet tagged, so I wouldn't suggest it) you can used named routes and check against the names of certain routes.

I'm guessing this is is in Klein 2 now? Can you give an example?

Here's my routes file if that helps.
https://github.com/funkytaco/php-mvc/blob/master/src/Routes.php

**Comment by imolorhe** [comment]
@Rican7 Can you give an example of instantiating and using controller classes with the `with()` group. The examples in the docs don't instantiate classes.

**Comment by funkytaco** [comment]
Still interested in seeing an example. Here are my routes.


    $IndexCtrl = $injector->make('Main\Controllers\IndexController');

    return [

        ['GET', '/', [$IndexCtrl, 'get']],
        ['GET', '/about', [$IndexCtrl, 'getAbout']],
        ['GET', '/contact', [$IndexCtrl, 'getContact']],
        ['GET', '/zenoss', [$ZenossCtrl, 'get']]

    ];


`Klein\Request` and `Klein\Response` are passed into the controllers "get" functions.
