### ISSUE TITLE
[onHttpError] $code differs to actual http code.

### ISSUE THREAD

**Issue by sweiguny** [klein/klein.php#187]
i am a little bit testing and i am on error handling. i noticed, that calling the method `$klein->abort(405);` with the following handler ...

``` php
$klein->onHttpError(function ($code, $router, $matched, $method_matched, $http_exception) {
    $router->response()->unlock();
    echo($code);

    switch ($code) {
        case 404:
            $router->response()->body('Y U so lost?!');
            break;
        case 405:
            $router->response()->body('You can\'t do that!');
            break;
        default:
            $router->response()->body('Oh no, a bad error happened that caused a'.$code);
    }
});
```

... results in that: http-code **405** as expected, but **404** in `$code` variable.

![image](https://f.cloud.github.com/assets/6470636/2264526/90937c22-9e73-11e3-95f9-0e714ddb914b.png)

am i doing something wrong?

---

**BTW:**
- is there a need to use the `$router->response()->body()?` function?
- Is and if, why is that a recommended way?
- an extra call to `$router->response()->unlock();` seems unconfortable to me...

so many questions :smiley:

**Comment by aolko** [comment]
Still happens,
```
var_dump($router->response()->code()); // 302
var_dump($code);                       // 404
```
