### ISSUE TITLE
A more detailed explanation on views (partial views, layouts etc)

### ISSUE THREAD

**Issue by niranjan94** [klein/klein.php#271]
A more detailed explanation on views (partial views, layouts etc) would be very much useful. The current README and wiki provided has very less info on how to implement layouts and partial views.

**Comment by nbish11** [comment]
Here, I just created a Wiki with some basic usage. I will create a more in depth one when I get some free time. [Views, Partials and Layouts](https://github.com/chriso/klein.php/wiki/Views,-Partials-and-Layouts)

**Comment by Rican7** [comment]
Thank you so much @nbish11! I really appreciate it!

**Comment by nbish11** [comment]
No problem. I'm pretty busy for the next couple of weeks, but if you want I could start updating the wiki when I'm next free.

**Comment by Rican7** [comment]
The more contributions, the better. I'll always appreciate help. :smiley:
