### ISSUE TITLE
Can't pass a variable in view.

### ISSUE THREAD

**Issue by gPaxbit** [klein/klein.php#343]
Maybe I don't understand smth., but this isn't working:

```
$variable = 'smb.';
$klein->respond('GET', '/', function($request, $response, $service) {
    $service->variable = $variable;
    $service->render('/view/view.php');
})
```
And am trying get it in `view.php` as:
```
<?= $this->variable ?>
```

and... nothing happens.

_PS: with superglobals its works perfectly._

**Comment by psrafo** [comment]
You need to define the variable as global in the start of callback function.

**Comment by gPaxbit** [comment]
thanx
