### ISSUE TITLE
Installing problems

### ISSUE THREAD

**Issue by maganius** [klein/klein.php#344]
Im trying install this library via composer but always I receive this error:

composer require klein/klein

Using version ^2.1 for klein/klein
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package klein/klein No version set (parsed as 1.0.0) is satisfiable by klein/klein[No version set (parsed as 1
.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

And in "vendor" the folder klein does not exists.

**Comment by bmd** [comment]
I can't reproduce this problem at all in a clean repo. Try setting the version explicitly in your require, like:

```
composer require klein/klein:2.1.1
```

**Comment by maganius** [comment]
Thanks now with the version definition its working.
