### ISSUE TITLE
Case insensitive

### ISSUE THREAD

**Issue by sm2017** [klein/klein.php#350]
How can I do this?

```php
$klein->respond('/check/[:name]', function ($request) {
    return 'Hello ' . $request->name;
});
```

```/check``` must be case insensitive but ```[:name]``` is case sensitive
Also ```/check/test``` is working but ```/check/test/``` is 404 I want to have both

**Comment by sm2017** [comment]
Any idea?

**Comment by jahak7** [comment]
@sm2017 
```php
require_once 'vendor/autoload.php';

use Klein\Klein;

$app = new Klein();
$app->respond('/check/[:name]/?', function ($request) {
    return 'Hello ' . $request->name;
});
$app->dispatch();
```

**Comment by sm2017** [comment]
@jahak7 thanks for your reply

```/check``` must be case insensitive but in your code is case sensitive

**Comment by thinsoldier** [comment]
Loop through the various url related values within $_SERVER and force them to be lowercase before your create your $klein object.

**Comment by sm2017** [comment]
Ok , thanks
