### ISSUE TITLE
Do we have Template engine only which we are using

### ISSUE THREAD

**Issue by ranapartap** [klein/klein.php#365]
Hi, Really a good router, 

Do we have Template Engine only any library, where we can use "yield" "partails" with template tags like "{var}" 

That could be a good for core php users.

Thank you in advance

**Comment by stanleybenjamin** [comment]
Like they said it is used for rapid project. You could use Twig engine or any other view engine for rendering

**Comment by Rican7** [comment]
Sorry, but yea, this is a bit out-of-scope for this project.

The included functionality is already a _bit_ too vast. I'd suggest using a separate template parser/renderer for that type of work.

Thanks!
